//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blotter.ReferenceData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceData.IReferenceDataService")]
    public interface IReferenceDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetCounterparties", ReplyAction="http://tempuri.org/IReferenceDataService/GetCounterpartiesResponse")]
        Blotter.Model.Counterparty[] GetCounterparties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetCounterparties", ReplyAction="http://tempuri.org/IReferenceDataService/GetCounterpartiesResponse")]
        System.Threading.Tasks.Task<Blotter.Model.Counterparty[]> GetCounterpartiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetSecurities", ReplyAction="http://tempuri.org/IReferenceDataService/GetSecuritiesResponse")]
        Blotter.Model.Security[] GetSecurities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetSecurities", ReplyAction="http://tempuri.org/IReferenceDataService/GetSecuritiesResponse")]
        System.Threading.Tasks.Task<Blotter.Model.Security[]> GetSecuritiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReferenceDataServiceChannel : Blotter.ReferenceData.IReferenceDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReferenceDataServiceClient : System.ServiceModel.ClientBase<Blotter.ReferenceData.IReferenceDataService>, Blotter.ReferenceData.IReferenceDataService {
        
        public ReferenceDataServiceClient() {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Blotter.Model.Counterparty[] GetCounterparties() {
            return base.Channel.GetCounterparties();
        }
        
        public System.Threading.Tasks.Task<Blotter.Model.Counterparty[]> GetCounterpartiesAsync() {
            return base.Channel.GetCounterpartiesAsync();
        }
        
        public Blotter.Model.Security[] GetSecurities() {
            return base.Channel.GetSecurities();
        }
        
        public System.Threading.Tasks.Task<Blotter.Model.Security[]> GetSecuritiesAsync() {
            return base.Channel.GetSecuritiesAsync();
        }
    }
}
